#!/usr/bin/env ruby

# written 2012 by tpltnt
# License: GPLv3

if 1 != ARGV.length then
  puts "wrong number of arguments"
  exit 1
end

begin
  dump = File.open(ARGV[0].to_s)
rescue Errno::ENOENT
  puts "file not found"
  exit 1
end

messagestobedeleted = []
# iterate over all lines
dump.each do |line|
  # filter out all sane line
  if nil != line.match(/.*\@.*\s\(.*\)/) then
    # match against "deleted" flag
    if nil != line.match(/deleted/) then
      # split at "deleted" and get first chunk of chars & add to list of messages
      messagestobedeleted.push( line.split(/deleted/)[0].split(" ")[0] )
    end
  end
end

dump.close

#TODO:
# find messages & delete them
# kill messges from dump

exit 0
