#!/usr/bin/env ruby

# written 2012 by tpltnt
# License: GPLv3

if 1 != ARGV.length then
  puts "wrong number of arguments"
  exit 1
end

begin
  dump = File.open(ARGV[0].to_s)
rescue Errno::ENOENT
  puts "file not found"
  exit 1
end

messagestobedeleted = []
# iterate over all lines
dump.each do |line|
  # filter out all sane line
  if nil != line.match(/.*\@.*\s\(.*\)/) then
      #
  end
end

dump.close
exit 0
